### ISSUE TITLE
Reconfigure Home Page of GitGinie 

### ISSUE THREAD

**Issue by kunjgit** [kunjgit/GitGinie#3]

**Comment by kunjgit** [comment]
@dishamodi0910 are you having anything interesting in your mind to implement on home page ?

**Comment by dishamodi0910** [comment]
@kunjgit Here is what I am thinking : 

1. Text [Welcome to GitGinie] with Hero Highlight and Highlight factor is on GitGinie.
2. The icon that we are already having right now(the logo)
3. Card grid for "Why GitGinie?" -> Have the animation on entire card grid as image attached.
Have the text reveal effect on the title of each card.
4. Have the scroll reveal effect on entire page.

![image](https://github.com/kunjgit/GitGinie/assets/106090499/e380ad41-d74f-49d8-b755-736a22fc32d3)

**Comment by dishamodi0910** [comment]
I can try implementing it out, if it looks good @kunjgit

**Comment by kunjgit** [comment]
@dishamodi0910 go ahead with it! 
Current one is not looking good?

**Comment by dishamodi0910** [comment]
@kunjgit Current one also looks good to me.
We can keep this one too.

**Comment by kunjgit** [comment]
@dishamodi0910 we will make enhancement as you told with current components in it

**Comment by dishamodi0910** [comment]
@kunjgit Some changes are pushed on the home page. I have modified the bento grid and added scroll animation along with animation for heading. Check UI Branch

**Comment by kunjgit** [comment]
done !
